pg_default: &pg_default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV["DB_POOL"] || ENV["MAX_THREADS"] || 20 %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000

default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3
  min_messages: warning

production: &deploy
  url: <%= ENV["DATABASE_URL"] %>
